### ISSUE TITLE
MIDI application crashes with no audio devices

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#42]
Since Microsoft GS Wavetable Synth doesn't crash a MIDI application with no audio devices installed on the computer or all audio devices are unplugged, Keppy's Synthesizer has a bug that crashes a MIDI application when using with no audio devices on the computer. However, "Output to WAV" has no effect though.

**Comment by KaleidonKep99** [comment]
Fixed as of [**version 4.0.4.9**](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.4.9).

**Comment by DevanWolf** [comment]
But I still get a crash when I start BRELS MIDI Editor, so the bug is still not fixed.

**Comment by KaleidonKep99** [comment]
It doesn't crash for me.
![image](https://cloud.githubusercontent.com/assets/11065274/20804109/e723ed20-b7f1-11e6-92ef-9d19a5c842e9.png)

**Comment by KaleidonKep99** [comment]
Same for this.
![image](https://cloud.githubusercontent.com/assets/11065274/20804149/0c3e4696-b7f2-11e6-89c1-bbe179a0fab9.png)

**Comment by DevanWolf** [comment]
I'll post a screenshot. It did on 32 bit version.

**Comment by KaleidonKep99** [comment]
Devan, BRELS uses the 32-bit driver, no matter which OS you use.

**Comment by DevanWolf** [comment]
Maybe you have XAudio disabled. Mine crashes when XAudio is enabled.
